import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const nunito = localFont({
  src: "../public/Nunito-Bold.ttf",
  weight: "700",
  style: "normal",
  variable: "--font-nunito",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${nunito.variable} antialiased`}>
      <body className="font-nunito">{children}</body>
    </html>
  );
}
